name: Build and Deploy
on:
  push:
    branches:
      - main
      - gh-test
  pull_request:
    branches:
      - main
      - gh-test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache pnpm store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          # pnpm store (cache files) are stored in `~/.npm` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npx pnpm i --store=~/.pnpm-store

      - name: Build
        run: npx pnpm run build

      - name: Deploy to current repository
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: gh-pages
          folder: dist # The folder the action should deploy.

      - name: Deploy to homepage repository
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          repository-name: quangkr/quangkr.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: dist # The folder the action should deploy.
