name: Build and Deploy
on:
  push:
    branches:
      - main
      - test-build
  pull_request:
    branches:
      - main
      - test-build
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and Build
        run: |
          npx pnpm i --store=node_modules/.pnpm-store
          npx pnpm run build

      - name: Deploy to current repository
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist # The folder the action should deploy.

      - name: Deploy to homepage repository
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          repository-name: quangkr/quangkr.github.io
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          branch: gh-pages
          folder: dist # The folder the action should deploy.
